FROM mysql:5.5

VOLUME /mySQL
ENV MYSQL_ROOT_PASSWORD=root

ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=computer-database-db
ENV MYSQL_USER=admincdb
ENV MYSQL_PASSWORD=qwerty1234


CMD /etc/init.d/mysql start
